## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(100)

City_ID  City_ID.4  City_ID.3  City_ID.2  City_ID.1           City  \
0         0          0          0          0          0     Bredasdorp   
1         1          1          1          1          2   Puerto Ayora   
2         3          3          3          3          4          Bluff   
3         4          4          4          4          6    East London   
4         5          5          5          5          7  Cockburn Town   
..      ...        ...        ...        ...        ...            ...   
95      102        102        102        102        126        Mayumba   
96      103        103        103        103        127         Hasaki   
97      104        104        104        104        128           Hilo   
98      106        106        106        106        130    Porto Velho   
99      107        107        107        107        131        Isangel   

   Country Weather Description  Max Temp      Lat       Lng  \
0       ZA          light rain     53.17 -34.5322   20.0403   
1       EC       broken clouds     69.55  -0.7393  -90.3518   
2       NZ          light rain     57.79 -46.6000  168.3333   
3       ZA          few clouds     58.96 -33.0153   27.9116   
4       TC          few clouds     81.66  21.4612  -71.1419   
..     ...                 ...       ...      ...       ...   
95      GA          few clouds     67.89  -3.4320   10.6554   
96      JP     overcast clouds     82.29  35.7333  140.8333   
97      US                mist     79.29  19.7297 -155.0900   
98      BR          few clouds     73.45  -8.7619  -63.9039   
99      VU          few clouds     78.71 -19.5500  169.2667   

                                       Hotel Name  
0                        Bredasdorp Country Manor  
1                       Finch Bay Galapagos Hotel  
2   Bluff Homestead - Guesthouse & Campervan Park  
3                                         Tu Casa  
4                              Osprey Beach Hotel  
..                                            ...  
95                                  LIKWALE LODGE  
96                          Inubosaki Kanko Hotel  
97                            Hilo Hawaiian Hotel  
98                            Ecos Hotel Conforto  
99                                    Tanna Lodge  

[100 rows x 12 columns]

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] =="Bluff")]
vacation_end = vacation_df.loc[(vacation_df["City"] =="Bluff")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] =="Tuatapere")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] =="Mataura")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] =="Kaitangata")] 


In [6]:
vacation_start = vacation_df.loc[(vacation_df["City"] =="Bluff")]
vacation_start

City_ID  City_ID.4  City_ID.3  City_ID.2  City_ID.1   City Country  \
2        3          3          3          3          4  Bluff      NZ   

  Weather Description  Max Temp   Lat       Lng  \
2          light rain     57.79 -46.6  168.3333   

                                      Hotel Name  
2  Bluff Homestead - Guesthouse & Campervan Park

In [7]:
vacation_stop1 = vacation_df.loc[(vacation_df["City"] =="Tuatapere")]
vacation_stop1

City_ID  City_ID.4  City_ID.3  City_ID.2  City_ID.1       City Country  \
143      153        153        153        153        185  Tuatapere      NZ   

    Weather Description  Max Temp      Lat       Lng  \
143       moderate rain     53.02 -46.1333  167.6833   

                         Hotel Name  
143  Ron and Tony's Bed & Breakfast

In [8]:
vacation_stop2 = vacation_df.loc[(vacation_df["City"] =="Mataura")] 
vacation_stop2

City_ID  City_ID.4  City_ID.3  City_ID.2  City_ID.1     City Country  \
29       32         32         32         32         37  Mataura      NZ   

   Weather Description  Max Temp      Lat       Lng     Hotel Name  
29    scattered clouds     57.47 -46.1927  168.8643  Ellie's Villa

In [9]:
vacation_stop3 = vacation_df.loc[(vacation_df["City"] =="Kaitangata")]
vacation_stop3

City_ID  City_ID.4  City_ID.3  City_ID.2  City_ID.1        City Country  \
228      247        247        247        247        291  Kaitangata      NZ   

    Weather Description  Max Temp      Lat       Lng             Hotel Name  
228     overcast clouds     53.74 -46.2817  169.8464  Kaitangata Motor Camp

In [10]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy(), vacation_start["Lng"].to_numpy()
start

(array([-46.6]), array([168.3333]))

In [11]:
end = vacation_end["Lat"].to_numpy(), vacation_end["Lng"].to_numpy()
end

(array([-46.6]), array([168.3333]))

In [12]:
stop1 = vacation_stop1["Lat"].to_numpy(), vacation_stop1["Lng"].to_numpy()
stop1

(array([-46.1333]), array([167.6833]))

In [13]:
stop2 = vacation_stop2["Lat"].to_numpy(), vacation_stop2["Lng"].to_numpy()
stop2

(array([-46.1927]), array([168.8643]))

In [14]:
stop3 = vacation_stop3["Lat"].to_numpy(), vacation_stop3["Lng"].to_numpy()
stop3

(array([-46.2817]), array([169.8464]))

In [15]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
start = (-46.6, 168.3333)
end = (-46.6, 168.3333)
stop1 = (-46.1333, 167.6833)
stop2 = (-46.1927, 168.8643)
stop3 = (-46.2817, 169.8464)

fig = gmaps.figure()
round_trip = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(round_trip)
fig


Figure(layout=FigureLayout(height='420px'))

In [16]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID  City_ID.4  City_ID.3  City_ID.2  City_ID.1        City Country  \
0        3          3          3          3          4       Bluff      NZ   
1      153        153        153        153        185   Tuatapere      NZ   
2       32         32         32         32         37     Mataura      NZ   
3      247        247        247        247        291  Kaitangata      NZ   

  Weather Description  Max Temp      Lat       Lng  \
0          light rain     57.79 -46.6000  168.3333   
1       moderate rain     53.02 -46.1333  167.6833   
2    scattered clouds     57.47 -46.1927  168.8643   
3     overcast clouds     53.74 -46.2817  169.8464   

                                      Hotel Name  
0  Bluff Homestead - Guesthouse & Campervan Park  
1                 Ron and Tony's Bed & Breakfast  
2                                  Ellie's Villa  
3                          Kaitangata Motor Camp

In [17]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [21]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(-46, 170.0), zoom_level=7.4)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))